server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /api/v1/auth/${segment}

        - id: parking-service-public
          uri: lb://parking-service
          predicates:
            - Path=/api/v1/lots/search/**, /api/v1/lots/nearby/**, /api/v1/lots/city/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        - id: parking-service-public-single
          uri: lb://parking-service
          predicates:
            - Path=/api/v1/lots/{id:[0-9]+}
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        - id: parking-service-spots-public
          uri: lb://parking-service
          predicates:
            - Path=/api/v1/spots/lot/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        - id: parking-service
          uri: lb://parking-service
          predicates:
            - Path=/api/v1/lots/**, /api/v1/spots/**
          filters:
            - JwtAuthFilter
            - RewritePath=/api/v1/(?<segment>.*), /api/v1/${segment}

        - id: booking-vehicle-service
          uri: lb://booking-vehicle-service
          predicates:
            - Path=/api/v1/bookings/**, /api/v1/vehicles/**
          filters:
            - JwtAuthFilter

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - JwtAuthFilter

        - id: notification-analytics-service
          uri: lb://notification-analytics-service
          predicates:
            - Path=/api/v1/notifications/**, /api/v1/analytics/**
          filters:
            - JwtAuthFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:4201"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:admin}@${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:parkease-super-secret-key-256bits-minimum-required}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.parkease.gateway: DEBUG
